package dev.iconpippi.asciicraft.game.art.other

import dev.iconpippi.asciicraft.engine.Renderer
import dev.iconpippi.asciicraft.game.art.ASCIIArt
import java.awt.Color

/**
 * 22/9/2019
 * AsciiCraft title, located in the center of AsciiCraft logo
 *
 * @author IconPippi
 */
class ASCIICraftTitle(override var xPos: Int, override var yPos: Int) : ASCIIArt {

    override fun draw(render: Boolean) {
        Renderer.drawChar(xPos, yPos, '/', Color.RED)
        Renderer.drawChar(xPos+1, yPos, '_', Color.RED)
        Renderer.drawChar(xPos+2, yPos, '/', Color.RED)
        Renderer.drawChar(xPos+6, yPos, '\\', Color.RED)
        Renderer.drawChar(xPos+7, yPos, '_', Color.RED)
        Renderer.drawChar(xPos+8, yPos, '\\', Color.RED)
        Renderer.drawChar(xPos+9, yPos, '_', Color.RED)
        Renderer.drawChar(xPos+10, yPos, '_', Color.RED)
        Renderer.drawChar(xPos+11, yPos, '_', Color.RED)
        Renderer.drawChar(xPos+12, yPos, '/', Color.RED)
        Renderer.drawChar(xPos+13, yPos, '\\', Color.RED)
        Renderer.drawChar(xPos+14, yPos, '_', Color.RED)
        Renderer.drawChar(xPos+15, yPos, '_', Color.RED)
        Renderer.drawChar(xPos+16, yPos, '_', Color.RED)
        Renderer.drawChar(xPos+17, yPos, '|', Color.RED)
        Renderer.drawChar(xPos+18, yPos, '_', Color.RED)
        Renderer.drawChar(xPos+19, yPos, '|', Color.RED)
        Renderer.drawChar(xPos+20, yPos, '_', Color.RED)
        Renderer.drawChar(xPos+21, yPos, '|', Color.RED)
        Renderer.drawChar(xPos+22, yPos, '\\', Color.RED)
        Renderer.drawChar(xPos+23, yPos, '_', Color.RED)
        Renderer.drawChar(xPos+24, yPos, '_', Color.RED)
        Renderer.drawChar(xPos+25, yPos, '_', Color.RED)
        Renderer.drawChar(xPos+26, yPos, '_', Color.RED)
        Renderer.drawChar(xPos+27, yPos, '|', Color.RED)
        Renderer.drawChar(xPos+28, yPos, '_', Color.RED)
        Renderer.drawChar(xPos+29, yPos, '|', Color.RED)
        Renderer.drawChar(xPos+32, yPos, '\\', Color.RED)
        Renderer.drawChar(xPos+33, yPos, '_', Color.RED)
        Renderer.drawChar(xPos+34, yPos, '_', Color.RED)
        Renderer.drawChar(xPos+35, yPos, ',', Color.RED)
        Renderer.drawChar(xPos+36, yPos, '_', Color.RED)
        Renderer.drawChar(xPos+37, yPos, '|', Color.RED)
        Renderer.drawChar(xPos+38, yPos, '_', Color.RED)
        Renderer.drawChar(xPos+39, yPos, '|', Color.RED)
        Renderer.drawChar(xPos+42, yPos, '\\', Color.RED)
        Renderer.drawChar(xPos+43, yPos, '_', Color.RED)
        Renderer.drawChar(xPos+44, yPos, '_', Color.RED)
        Renderer.drawChar(xPos+45, yPos, '|', Color.RED)

        Renderer.drawChar(xPos+1, yPos-1, '/', Color.RED)
        Renderer.drawChar(xPos+3, yPos-1, '_', Color.RED)
        Renderer.drawChar(xPos+4, yPos-1, '_', Color.RED)
        Renderer.drawChar(xPos+5, yPos-1, '_', Color.RED)
        Renderer.drawChar(xPos+7, yPos-1, '\\', Color.RED)
        Renderer.drawChar(xPos+8, yPos-1, '\\', Color.RED)
        Renderer.drawChar(xPos+9, yPos-1, '_', Color.RED)
        Renderer.drawChar(xPos+10, yPos-1, '_', Color.RED)
        Renderer.drawChar(xPos+12, yPos-1, '\\', Color.RED)
        Renderer.drawChar(xPos+14, yPos-1, '(', Color.RED)
        Renderer.drawChar(xPos+15, yPos-1, '_', Color.RED)
        Renderer.drawChar(xPos+16, yPos-1, '_', Color.RED)
        Renderer.drawChar(xPos+17, yPos-1, '|', Color.RED)
        Renderer.drawChar(xPos+19, yPos-1, '|', Color.RED)
        Renderer.drawChar(xPos+21, yPos-1, '|', Color.RED)
        Renderer.drawChar(xPos+23, yPos-1, '|', Color.RED)
        Renderer.drawChar(xPos+24, yPos-1, '_', Color.RED)
        Renderer.drawChar(xPos+25, yPos-1, '_', Color.RED)
        Renderer.drawChar(xPos+26, yPos-1, '_', Color.RED)
        Renderer.drawChar(xPos+27, yPos-1, '|', Color.RED)
        Renderer.drawChar(xPos+29, yPos-1, '|', Color.RED)
        Renderer.drawChar(xPos+31, yPos-1, '|', Color.RED)
        Renderer.drawChar(xPos+33, yPos-1, '(', Color.RED)
        Renderer.drawChar(xPos+34, yPos-1, '_', Color.RED)
        Renderer.drawChar(xPos+35, yPos-1, '|', Color.RED)
        Renderer.drawChar(xPos+37, yPos-1, '|', Color.RED)
        Renderer.drawChar(xPos+40, yPos-1, '_', Color.RED)
        Renderer.drawChar(xPos+41, yPos-1, '|', Color.RED)
        Renderer.drawChar(xPos+43, yPos-1, '|', Color.RED)
        Renderer.drawChar(xPos+44, yPos-1, '_', Color.RED)

        Renderer.drawChar(xPos+2, yPos-2, '/', Color.RED)
        Renderer.drawChar(xPos+4, yPos-2, '_', Color.RED)
        Renderer.drawChar(xPos+6, yPos-2, '\\', Color.RED)
        Renderer.drawChar(xPos+8, yPos-2, '/', Color.RED)
        Renderer.drawChar(xPos+10, yPos-2, '_', Color.RED)
        Renderer.drawChar(xPos+11, yPos-2, '_', Color.RED)
        Renderer.drawChar(xPos+12, yPos-2, '|', Color.RED)
        Renderer.drawChar(xPos+13, yPos-2, '/', Color.RED)
        Renderer.drawChar(xPos+15, yPos-2, '_', Color.RED)
        Renderer.drawChar(xPos+16, yPos-2, '_', Color.RED)
        Renderer.drawChar(xPos+17, yPos-2, '|', Color.RED)
        Renderer.drawChar(xPos+19, yPos-2, '|', Color.RED)
        Renderer.drawChar(xPos+21, yPos-2, '|', Color.RED)
        Renderer.drawChar(xPos+23, yPos-2, '|', Color.RED)
        Renderer.drawChar(xPos+27, yPos-2, '|', Color.RED)
        Renderer.drawChar(xPos+29, yPos-2, '\'', Color.RED)
        Renderer.drawChar(xPos+30, yPos-2, '_', Color.RED)
        Renderer.drawChar(xPos+31, yPos-2, '_', Color.RED)
        Renderer.drawChar(xPos+32, yPos-2, '/', Color.RED)
        Renderer.drawChar(xPos+34, yPos-2, '_', Color.RED)
        Renderer.drawChar(xPos+35, yPos-2, '`', Color.RED)
        Renderer.drawChar(xPos+37, yPos-2, '|', Color.RED)
        Renderer.drawChar(xPos+39, yPos-2, '|', Color.RED)
        Renderer.drawChar(xPos+40, yPos-2, '_', Color.RED)
        Renderer.drawChar(xPos+41, yPos-2, '|', Color.RED)
        Renderer.drawChar(xPos+43, yPos-2, '_', Color.RED)
        Renderer.drawChar(xPos+44, yPos-2, '_', Color.RED)
        Renderer.drawChar(xPos+45, yPos-2, '|', Color.RED)

        Renderer.drawChar(xPos+3, yPos-3, '/', Color.RED)
        Renderer.drawChar(xPos+5, yPos-3, '\\', Color.RED)
        Renderer.drawChar(xPos+9, yPos-3, '_', Color.RED)
        Renderer.drawChar(xPos+10, yPos-3, '_', Color.RED)
        Renderer.drawChar(xPos+11, yPos-3, '_', Color.RED)
        Renderer.drawChar(xPos+14, yPos-3, '_', Color.RED)
        Renderer.drawChar(xPos+15, yPos-3, '_', Color.RED)
        Renderer.drawChar(xPos+16, yPos-3, '_', Color.RED)
        Renderer.drawChar(xPos+17, yPos-3, '(', Color.RED)
        Renderer.drawChar(xPos+18, yPos-3, '_', Color.RED)
        Renderer.drawChar(xPos+19, yPos-3, '|', Color.RED)
        Renderer.drawChar(xPos+20, yPos-3, '_', Color.RED)
        Renderer.drawChar(xPos+21, yPos-3, ')', Color.RED)
        Renderer.drawChar(xPos+22, yPos-3, '/', Color.RED)
        Renderer.drawChar(xPos+24, yPos-3, '_', Color.RED)
        Renderer.drawChar(xPos+25, yPos-3, '_', Color.RED)
        Renderer.drawChar(xPos+26, yPos-3, '_', Color.RED)
        Renderer.drawChar(xPos+27, yPos-3, '|', Color.RED)
        Renderer.drawChar(xPos+28, yPos-3, '_', Color.RED)
        Renderer.drawChar(xPos+30, yPos-3, '_', Color.RED)
        Renderer.drawChar(xPos+31, yPos-3, '_', Color.RED)
        Renderer.drawChar(xPos+33, yPos-3, '_', Color.RED)
        Renderer.drawChar(xPos+34, yPos-3, '_', Color.RED)
        Renderer.drawChar(xPos+36, yPos-3, '_', Color.RED)
        Renderer.drawChar(xPos+38, yPos-3, '/', Color.RED)
        Renderer.drawChar(xPos+40, yPos-3, '_', Color.RED)
        Renderer.drawChar(xPos+41, yPos-3, '|', Color.RED)
        Renderer.drawChar(xPos+43, yPos-3, '|', Color.RED)
        Renderer.drawChar(xPos+44, yPos-3, '_', Color.RED)

        Renderer.drawChar(xPos+4, yPos-4, '_', Color.RED)
        Renderer.drawChar(xPos+18, yPos-4, '_', Color.RED)
        Renderer.drawChar(xPos+19, yPos-4, '_', Color.RED)
        Renderer.drawChar(xPos+23, yPos-4, '_', Color.RED)
        Renderer.drawChar(xPos+24, yPos-4, '_', Color.RED)
        Renderer.drawChar(xPos+25, yPos-4, '_', Color.RED)
        Renderer.drawChar(xPos+26, yPos-4, '_', Color.RED)
        Renderer.drawChar(xPos+39, yPos-4, '_', Color.RED)
        Renderer.drawChar(xPos+40, yPos-4, '_', Color.RED)
        Renderer.drawChar(xPos+42, yPos-4, '_', Color.RED)

        if (render) Renderer.renderScreen()
    }

}